# Generated by Django 5.2.1 on 2025-05-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='expense',
        ),
    ]
